### ISSUE TITLE
和我的想法差不多啊，连语法都类似~

### ISSUE THREAD

**Issue by lyb5834** [hon-key/Nudeln#12]
看我的开源框架 https://github.com/lyb5834/YBAttributeString  ，和你原理差不多，感觉可以互补下

**Comment by hon-key** [comment]
虽然都是声明式编程，不过区别还是挺大的
你这个是基于NSString来生成NSAttributedString，相对来说适用性更广泛一些
NudeIn是一款目标用来取代UILabel和UITextView的控件
不过想法都很好，支持支持
