### ISSUE TITLE
如何更新文本内容了

### ISSUE THREAD

**Issue by hjrcn** [hon-key/Nudeln#20]
如果数据是动态获取，根据接口不一样而变化，如果更新了？

**Comment by hon-key** [comment]
限于 NSAttributedString 的不可变，更新文本可以目前只能用 remake 功能进行更新，写一个方法，根据动态值来 remake 该文本。
需要注意两点：
1、因为 remake 是在主线程做的操作，如果你在性能敏感页面使用大量的 remake，可能会导致轻微降帧，这时候建议使用 asyncRemake
2、如果使用 asyncRemake，而且使用了 autolayout，由于 asyncRemake 通过 GCD 进行调度，而 GCD 在 dispatch 到主线程的时候使用的是 runloop，所以可能会让 NudeIn autolayout 在动画进行时变化从而产生隐式动画，这回导致NudeIn产生闪烁或跳动，需要注意
