### ISSUE TITLE
无法透传点击事件

### ISSUE THREAD

**Issue by hjrcn** [hon-key/Nudeln#22]
在UITableViewCell中使用,点击后didSelectRowAtIndexPath就不起效果了,被拦截了,有什么方法可以关闭吗?

**Comment by hon-key** [comment]
> 在UITableViewCell中使用,点击后didSelectRowAtIndexPath就不起效果了,被拦截了,有什么方法可以关闭吗?

如果你不打算让 NudeIn 接收任何事件的话：
可以将 NudeIn 的 userInteractionEnabled 设为 NO 以屏蔽事件的接收
如果你打算接收事件的话，比如对富文本的某一部分做事件的接收：
1. 对富文本的某一部分做事件接收
2. 对富文本的剩余部分做事件接收，并和 didSelectRowAtIndexPath 做一样的处理

**Comment by hon-key** [comment]
原因在于 UITextView 对 UIResponder 的实现会截断响应链

**Comment by hjrcn** [comment]
谢谢!之前是有想到要设置userInteractionEnabled,不过设置为Yes,搞错了,没起效果.
