### ISSUE TITLE
感谢作者的开源作品, 有个问题, 绑定点击事件相关.

### ISSUE THREAD

**Issue by guowilling** [hon-key/Nudeln#8]
我遇到个问题, 运行 textExample, 点击 BlueLink 没有任何效果, 点击事件没有绑定上吗?
麻烦你有空时帮忙看下, 谢谢.

**Comment by hon-key** [comment]
感谢你的提醒，这是当时开发的时候没做健全测试造成的，当时在做highlight的时候把selectable设置为了NO，这个属性的介绍也说了，它会影响原生的link属性，所以导致其不可点。
作为暂时的解决方法，你现在可以先暂时把初始化出来的NudeIn调用以下方法：
```
yourComp.selectable = YES
```
这个问题会在不久之后我发布新版本的时候解决。

**Comment by hon-key** [comment]
> 我遇到个问题, 运行 textExample, 点击 BlueLink 没有任何效果, 点击事件没有绑定上吗?
> 麻烦你有空时帮忙看下, 谢谢.

事实上，原生的link属性不是太好用，上面也说了，它需要selectable才能触发点击效果，之后的新版本会上线press和longpress，配合highlight可以做到完全自定义高亮效果，并且附带点击，不需要selectable

**Comment by hjrcn** [comment]
你好,我在UITableViewCell中使用,发现会屏蔽didSelectRowAtIndexPath事件,导致点击无效,请问如何解决?谢谢!
